// const layoutStyle: SxCssProperties = {
//   sideBarContainer: {
//     display: "flex",
//     flexDirection: "column",
//     height: "100vh",
//     width: "20%",
//     backgroundImage: (theme) =>
//       `linear-gradient(220deg,${theme.palette.primary.dark} , ${theme.palette.primary.light})`,
//     justifyContent: "space-between",
//     overflowY: "auto",
//     position: "fixed",
//     right: 0,
//     top: 0,
//     transition: "all 5s",
//   },
//   sideBarHeaderWrapper: {
//     display: "flex",
//     flexDirection: "column",
//     gap: 2,
//   },
//   sideBarHeader: {
//     display: "flex",
//     width: "100%",
//     alignItems: "center",
//     justifyContent: "space-between",
//     px: 2,
//     py: 1,
//   },
//   logo: {
//     display: "flex",
//     alignItems: "center",
//     justifyContent: "flex-start",
//   },
//   profileInfo: {
//     display: "flex",
//     alignItems: "center",
//     justifyContent: "flex-end",
//     gap: 1,
//   },
//   sideBarMenu: {
//     display: "flex",
//     alignItems: "flex-start",
//     flexDirection: "column",
//     gap: 1,
//     position: "relative",
//     width: "100%",
//   },
//   sideBarMenuWrapper: {
//     width: "100%",
//     height: "68vh",
//     overflowY: "auto",
//     display: "flex",
//     flexDirection: "column",
//     gap: 1.5,
//     px: 2,
//   },
//   sideBarItem: {
//     display: "flex",
//     alignItems: "center",
//     gap: 1,
//     justifyContent: "space-between",
//     padding: "0.6rem 0.9rem",
//     borderRadius: (theme) => theme.shape.borderRadius,
//     transition: "all 0.35s",
//     width: "100%",
//   },
//   sideBarSubMenuWrapper: {
//     display: "flex",
//     flexDirection: "column",
//     gap: 1,
//     p: 1,
//     bgcolor: "#00000018",
//     borderRadius: shape.borderRadius,
//     mt: 0.7,
//     mb: 0.5,
//     width: "100%",
//   },
//   collapseWrapper: {
//     width: "90%",
//     mx: "auto",
//   },
//   sideBarUnlockFeatureBox: {
//     width: "75%",
//     borderRadius: shape.borderRadius,
//     bgcolor: "#00000018",
//     display: "flex",
//     alignItems: "center",
//     flexDirection: "column",
//     gap: 1.5,
//     justifyContent: "center",
//     mx: "auto",
//     px: 3,
//     py: 1.5,
//   },
// };

// export default layoutStyle;
